Fix mqtt config, new port anaimation
Bedrock-Media-Designs/OXRS-BMD-SmokeDetector-ESP32-FW pull request #3
Opened 2021-09-23 18:08 UTC by moinmoin-sh

Updated for new SmokeDetector port animation 
I had to enable pullups for the input MCP because my breadboard doesn't have external pullups.

This requires the new LCD lib

2021-09-23 21:08 UTC, sumnerboy12 commented
Can you rebase this onto the `main` branch as I have since merged the `fix_mqtt_config` branch? Then this PR will only show the changes you have made.

2021-09-23 21:57 UTC, moinmoin-sh commented
I ried to rebase , does this look better?

2021-09-26 23:11 UTC, sumnerboy12 requested changes

2021-09-26 23:11 UTC, sumnerboy12 commented on OXRS-BMD-SmokeDetector-ESP32-FW.ino
> +      mcp23017[mcp].pinMode(pin, address == MCP_INPUT_ADDR ? INPUT_PULLUP : OUTPUT);
This needs to be reverted - the smoke detector hardware has h/w pullups built in so this shouldn't be in the firmware.

2021-09-27 02:48 UTC, sumnerboy12 commented
I inadvertently merged this when I migrated to the new Rack32 library - sorry!

2021-09-27 02:48 UTC, closed without merging